
services:
  jenkins:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    privileged: true 
    volumes:
      - ./jenkins_home/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: unless-stopped
